language: node_js
node_js:
  - 0.10
services:
  - mongodb
before_script:
  - npm install -g grunt-cli
notifications:
  email:
    recipients:
      - eduar.diaz37@gmail.com
    on_success: always
    on_failure: always
